CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(32) NOT NULL UNIQUE,
  email VARCHAR(256) NOT NULL UNIQUE,
  password TEXT NOT NULL,
  avatar_url TEXT DEFAULT NULL,
  status VARCHAR(16) DEFAULT 'offline',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  last_login TIMESTAMP DEFAULT NULL,
  is_verified BOOLEAN DEFAULT FALSE,
  is_disabled BOOLEAN DEFAULT FALSE
);